version: '3.8'

services:
  lie-detector-viewer:
    build: .
    ports:
      - "9009:9009"
    volumes:
      - /mnt/nvme3/dipika/lie-detector:/data:ro  # Mount your data directory as read-only
    environment:
      - FLASK_ENV=production
    restart: unless-stopped 